//! Known `@devup-ui/react` primitive prop names, taken from devup-ui's own
//! source rather than invented: the keys of every `ResponsiveValue` prop in
//! `packages/react/src/types/props/*.ts` and every alias in
//! `libs/css/src/constant.rs`, at devup-ui 1.0.41 (e407524), plus the
//! entries the published Style Props API reference listed before that. The
//! docs page alone was 409 props short — `maskPos`, `bgPos`,
//! `WebkitLineClamp`, `visibility`, `zoom` among them — and the plugin writes
//! `maskPos` on every mask icon, so `devup_ui_validate` was rejecting real
//! devup-ui code as `unknown-prop`. `devup_ui_validate`'s `unknown-prop`
//! rule checks JSX attributes on the primitive elements it recognizes
//! (`Box`, `Flex`, `Text`, `Center`, `Grid`, `Image`) against this list plus
//! a small set of standard React/HTML/devup-ui-specific non-style props;
//! anything else is flagged rather than guessed at.
//!
//! `DEVUP_COLOR_LIKE_PROPS` / `DEVUP_LENGTH_LIKE_PROPS` are the subsets
//! whose CSS-property counterpart is a single color or length value; they
//! drive the `hardcoded-color` / `hardcoded-length` / `unknown-token`
//! rules. Deliberately conservative: composite props like `background`
//! (can hold a gradient) or `border` (shorthand for width+style+color) are
//! excluded from both subsets rather than guessed at, since flagging them
//! incorrectly would repeat exactly the fabrication failure this tool
//! exists to prevent.

/// devup-ui primitive components whose JSX props this validator checks
/// against [`DEVUP_STYLE_PROPS`] for the `unknown-prop` rule. Custom
/// component names are never flagged: unlike these primitives, a custom
/// component's valid prop set cannot be known statically from devup-ui's
/// public docs, so guessing which props it accepts would risk exactly the
/// kind of invented-fact failure this tool exists to prevent.
pub const DEVUP_PRIMITIVE_ELEMENTS: &[&str] = &["Box", "Flex", "Text", "Center", "Grid", "Image"];

/// Non-style props every devup-ui primitive additionally accepts: standard
/// React/HTML attributes, event handlers, and devup-ui-specific structural
/// props (`as`, `selectors`). Checked case-sensitively against the exact
/// attribute name; `data-*`/`aria-*` and pseudo-state (`_hover`, `_dark`,
/// ...) / responsive-condition props are matched by prefix separately in
/// `is_known_non_style_prop`.
const DEVUP_NON_STYLE_PROPS: &[&str] = &[
    "as",
    "selectors",
    "children",
    "className",
    "style",
    "id",
    "key",
    "ref",
    "role",
    "tabIndex",
    "title",
    "htmlFor",
    "for",
    "colSpan",
    "rowSpan",
    "type",
    "name",
    "value",
    "defaultValue",
    "placeholder",
    "disabled",
    "checked",
    "defaultChecked",
    "readOnly",
    "required",
    "min",
    "max",
    "step",
    "rows",
    "cols",
    "src",
    "srcSet",
    "alt",
    "sizes",
    "loading",
    "decoding",
    "href",
    "target",
    "rel",
    "download",
    "autoFocus",
    "autoComplete",
    "form",
    "multiple",
    "accept",
    "list",
    "pattern",
    "spellCheck",
    "draggable",
    "contentEditable",
    "suppressHydrationWarning",
];

/// Returns true for props no primitive-specific check should ever flag:
/// standard React/HTML attributes, `on*` event handlers, `data-*`/`aria-*`,
/// and devup-ui pseudo-state / responsive-condition props (which are
/// user-defined selector keys, not a fixed enumerable set).
pub fn is_known_non_style_prop(name: &str) -> bool {
    DEVUP_NON_STYLE_PROPS.contains(&name)
        || name.starts_with("on")
        || name.starts_with("data-")
        || name.starts_with("aria-")
        || name.starts_with('_')
}

pub fn is_known_style_prop(name: &str) -> bool {
    DEVUP_STYLE_PROPS.binary_search(&name).is_ok()
}

pub fn is_color_like_prop(name: &str) -> bool {
    DEVUP_COLOR_LIKE_PROPS.binary_search(&name).is_ok()
}

pub fn is_length_like_prop(name: &str) -> bool {
    DEVUP_LENGTH_LIKE_PROPS.binary_search(&name).is_ok()
}

pub const DEVUP_STYLE_PROPS: &[&str] = &[
    "MozAppearance",
    "MozBinding",
    "MozBorderBottomColors",
    "MozBorderLeftColors",
    "MozBorderRightColors",
    "MozBorderTopColors",
    "MozBoxAlign",
    "MozBoxDirection",
    "MozBoxFlex",
    "MozBoxFlexGroup",
    "MozBoxLines",
    "MozBoxOrdinalGroup",
    "MozBoxOrient",
    "MozBoxPack",
    "MozContextProperties",
    "MozFloatEdge",
    "MozForceBrokenImageIcon",
    "MozOrient",
    "MozOutlineRadius",
    "MozOutlineRadiusBottomleft",
    "MozOutlineRadiusBottomright",
    "MozOutlineRadiusTopleft",
    "MozOutlineRadiusTopright",
    "MozOverflowClipBox",
    "MozStackSizing",
    "MozTextBlink",
    "MozUserFocus",
    "MozUserInput",
    "MozUserModify",
    "MozWindowDragging",
    "MozWindowShadow",
    "WebkitAppearance",
    "WebkitBorderAfter",
    "WebkitBorderAfterColor",
    "WebkitBorderAfterStyle",
    "WebkitBorderAfterWidth",
    "WebkitBorderBefore",
    "WebkitBorderBeforeColor",
    "WebkitBorderBeforeStyle",
    "WebkitBorderBeforeWidth",
    "WebkitBorderEnd",
    "WebkitBorderEndColor",
    "WebkitBorderEndStyle",
    "WebkitBorderEndWidth",
    "WebkitBorderStart",
    "WebkitBorderStartColor",
    "WebkitBorderStartStyle",
    "WebkitBorderStartWidth",
    "WebkitBoxAlign",
    "WebkitBoxDirection",
    "WebkitBoxFlex",
    "WebkitBoxFlexGroup",
    "WebkitBoxLines",
    "WebkitBoxOrdinalGroup",
    "WebkitBoxOrient",
    "WebkitBoxPack",
    "WebkitBoxReflect",
    "WebkitLineClamp",
    "WebkitMask",
    "WebkitMaskAttachment",
    "WebkitMaskClip",
    "WebkitMaskComposite",
    "WebkitMaskImage",
    "WebkitMaskOrigin",
    "WebkitMaskPosition",
    "WebkitMaskPositionX",
    "WebkitMaskPositionY",
    "WebkitMaskRepeat",
    "WebkitMaskRepeatX",
    "WebkitMaskRepeatY",
    "WebkitMaskSize",
    "WebkitOverflowScrolling",
    "WebkitTapHighlightColor",
    "WebkitTextFillColor",
    "WebkitTextStroke",
    "WebkitTextStrokeColor",
    "WebkitTextStrokeWidth",
    "WebkitTouchCallout",
    "WebkitUserModify",
    "WebkitUserSelect",
    "accentColor",
    "alignContent",
    "alignItems",
    "alignSelf",
    "alignTracks",
    "alignmentBaseline",
    "all",
    "anchorName",
    "anchorScope",
    "animation",
    "animationComposition",
    "animationDelay",
    "animationDir",
    "animationDirection",
    "animationDuration",
    "animationFillMode",
    "animationIterationCount",
    "animationName",
    "animationPlayState",
    "animationRange",
    "animationRangeEnd",
    "animationRangeStart",
    "animationTimeline",
    "animationTimingFunction",
    "animationTrigger",
    "appearance",
    "aspectRatio",
    "backdropFilter",
    "backfaceVisibility",
    "background",
    "backgroundAttachment",
    "backgroundBlendMode",
    "backgroundClip",
    "backgroundColor",
    "backgroundImage",
    "backgroundImg",
    "backgroundOrigin",
    "backgroundPosition",
    "backgroundPositionX",
    "backgroundPositionY",
    "backgroundRepeat",
    "backgroundSize",
    "baselineShift",
    "baselineSource",
    "bg",
    "bgAttachment",
    "bgBlendMode",
    "bgClip",
    "bgColor",
    "bgImage",
    "bgImg",
    "bgOrigin",
    "bgPos",
    "bgPosX",
    "bgPosY",
    "bgPosition",
    "bgPositionX",
    "bgPositionY",
    "bgRepeat",
    "bgSize",
    "blockSize",
    "border",
    "borderBlock",
    "borderBlockColor",
    "borderBlockEnd",
    "borderBlockEndColor",
    "borderBlockEndStyle",
    "borderBlockEndWidth",
    "borderBlockStart",
    "borderBlockStartColor",
    "borderBlockStartStyle",
    "borderBlockStartWidth",
    "borderBlockStyle",
    "borderBlockWidth",
    "borderBottom",
    "borderBottomColor",
    "borderBottomLeftRadius",
    "borderBottomRadius",
    "borderBottomRightRadius",
    "borderBottomStyle",
    "borderBottomWidth",
    "borderCollapse",
    "borderColor",
    "borderEndEndRadius",
    "borderEndStartRadius",
    "borderImage",
    "borderImageOutset",
    "borderImageRepeat",
    "borderImageSlice",
    "borderImageSource",
    "borderImageWidth",
    "borderInline",
    "borderInlineColor",
    "borderInlineEnd",
    "borderInlineEndColor",
    "borderInlineEndStyle",
    "borderInlineEndWidth",
    "borderInlineStart",
    "borderInlineStartColor",
    "borderInlineStartStyle",
    "borderInlineStartWidth",
    "borderInlineStyle",
    "borderInlineWidth",
    "borderLeft",
    "borderLeftColor",
    "borderLeftRadius",
    "borderLeftStyle",
    "borderLeftWidth",
    "borderRadius",
    "borderRight",
    "borderRightColor",
    "borderRightRadius",
    "borderRightStyle",
    "borderRightWidth",
    "borderShape",
    "borderSpacing",
    "borderStartEndRadius",
    "borderStartStartRadius",
    "borderStyle",
    "borderTop",
    "borderTopColor",
    "borderTopLeftRadius",
    "borderTopRadius",
    "borderTopRightRadius",
    "borderTopStyle",
    "borderTopWidth",
    "borderWidth",
    "bottom",
    "boxAlign",
    "boxDecorationBreak",
    "boxDirection",
    "boxFlex",
    "boxFlexGroup",
    "boxLines",
    "boxOrdinalGroup",
    "boxOrient",
    "boxPack",
    "boxShadow",
    "boxSize",
    "boxSizing",
    "breakAfter",
    "breakBefore",
    "breakInside",
    "captionSide",
    "caret",
    "caretAnimation",
    "caretColor",
    "caretShape",
    "clear",
    "clip",
    "clipPath",
    "clipRule",
    "color",
    "colorInterpolationFilters",
    "colorScheme",
    "columnCount",
    "columnFill",
    "columnGap",
    "columnHeight",
    "columnRule",
    "columnRuleColor",
    "columnRuleStyle",
    "columnRuleWidth",
    "columnSpan",
    "columnWidth",
    "columnWrap",
    "columns",
    "contain",
    "containIntrinsicBlockSize",
    "containIntrinsicHeight",
    "containIntrinsicInlineSize",
    "containIntrinsicSize",
    "containIntrinsicWidth",
    "container",
    "containerName",
    "containerType",
    "content",
    "contentVisibility",
    "cornerBlockEndShape",
    "cornerBlockStartShape",
    "cornerBottomLeftShape",
    "cornerBottomRightShape",
    "cornerBottomShape",
    "cornerEndEndShape",
    "cornerEndStartShape",
    "cornerInlineEndShape",
    "cornerInlineStartShape",
    "cornerLeftShape",
    "cornerRightShape",
    "cornerShape",
    "cornerStartEndShape",
    "cornerStartStartShape",
    "cornerTopLeftShape",
    "cornerTopRightShape",
    "cornerTopShape",
    "counterIncrement",
    "counterReset",
    "counterSet",
    "cursor",
    "cx",
    "cy",
    "d",
    "direction",
    "display",
    "dominantBaseline",
    "dynamicRangeLimit",
    "emptyCells",
    "fieldSizing",
    "fill",
    "fillOpacity",
    "fillRule",
    "filter",
    "flex",
    "flexBasis",
    "flexDir",
    "flexDirection",
    "flexFlow",
    "flexGrow",
    "flexLineCount",
    "flexShrink",
    "flexWrap",
    "float",
    "floodColor",
    "floodOpacity",
    "font",
    "fontFamily",
    "fontFeatureSettings",
    "fontKerning",
    "fontLanguageOverride",
    "fontOpticalSizing",
    "fontPalette",
    "fontSize",
    "fontSizeAdjust",
    "fontSmooth",
    "fontStretch",
    "fontStyle",
    "fontSynthesis",
    "fontSynthesisPosition",
    "fontSynthesisSmallCaps",
    "fontSynthesisStyle",
    "fontSynthesisWeight",
    "fontVariant",
    "fontVariantAlternates",
    "fontVariantCaps",
    "fontVariantEastAsian",
    "fontVariantEmoji",
    "fontVariantLigatures",
    "fontVariantNumeric",
    "fontVariantPosition",
    "fontVariationSettings",
    "fontWeight",
    "fontWidth",
    "forcedColorAdjust",
    "frameSizing",
    "gap",
    "grid",
    "gridArea",
    "gridAutoColumns",
    "gridAutoFlow",
    "gridAutoRows",
    "gridColumn",
    "gridColumnEnd",
    "gridColumnGap",
    "gridColumnStart",
    "gridGap",
    "gridRow",
    "gridRowEnd",
    "gridRowGap",
    "gridRowStart",
    "gridTemplate",
    "gridTemplateAreas",
    "gridTemplateColumns",
    "gridTemplateRows",
    "h",
    "hangingPunctuation",
    "height",
    "hyphenateCharacter",
    "hyphenateLimitChars",
    "hyphens",
    "imageOrientation",
    "imageRendering",
    "imageResolution",
    "imeMode",
    "initialLetter",
    "initialLetterAlign",
    "inlineSize",
    "inset",
    "insetBlock",
    "insetBlockEnd",
    "insetBlockStart",
    "insetInline",
    "insetInlineEnd",
    "insetInlineStart",
    "interactivity",
    "interestDelay",
    "interestDelayEnd",
    "interestDelayStart",
    "interpolateSize",
    "isolation",
    "justifyContent",
    "justifyItems",
    "justifySelf",
    "justifyTracks",
    "left",
    "letterSpacing",
    "lightingColor",
    "lineBreak",
    "lineClamp",
    "lineHeight",
    "lineHeightStep",
    "linkParameters",
    "listStyle",
    "listStyleImage",
    "listStylePosition",
    "listStyleType",
    "m",
    "margin",
    "marginBlock",
    "marginBlockEnd",
    "marginBlockStart",
    "marginBottom",
    "marginInline",
    "marginInlineEnd",
    "marginInlineStart",
    "marginLeft",
    "marginRight",
    "marginTop",
    "marginTrim",
    "marker",
    "markerEnd",
    "markerMid",
    "markerStart",
    "mask",
    "maskBorder",
    "maskBorderMode",
    "maskBorderOutset",
    "maskBorderRepeat",
    "maskBorderSlice",
    "maskBorderSource",
    "maskBorderWidth",
    "maskClip",
    "maskComposite",
    "maskImage",
    "maskImg",
    "maskMode",
    "maskOrigin",
    "maskPos",
    "maskPosition",
    "maskRepeat",
    "maskSize",
    "maskType",
    "masonryAutoFlow",
    "mathDepth",
    "mathShift",
    "mathStyle",
    "maxBlockSize",
    "maxH",
    "maxHeight",
    "maxInlineSize",
    "maxLines",
    "maxW",
    "maxWidth",
    "mb",
    "minBlockSize",
    "minH",
    "minHeight",
    "minInlineSize",
    "minW",
    "minWidth",
    "mixBlendMode",
    "ml",
    "mr",
    "msAccelerator",
    "msBlockProgression",
    "msContentZoomChaining",
    "msContentZoomLimit",
    "msContentZoomLimitMax",
    "msContentZoomLimitMin",
    "msContentZoomSnap",
    "msContentZoomSnapPoints",
    "msContentZoomSnapType",
    "msContentZooming",
    "msFilter",
    "msFlowFrom",
    "msFlowInto",
    "msGridColumns",
    "msGridRows",
    "msHighContrastAdjust",
    "msHyphenateLimitChars",
    "msHyphenateLimitLines",
    "msHyphenateLimitZone",
    "msImeAlign",
    "msOverflowStyle",
    "msScrollChaining",
    "msScrollLimit",
    "msScrollLimitXMax",
    "msScrollLimitXMin",
    "msScrollLimitYMax",
    "msScrollLimitYMin",
    "msScrollRails",
    "msScrollSnapPointsX",
    "msScrollSnapPointsY",
    "msScrollSnapType",
    "msScrollSnapX",
    "msScrollSnapY",
    "msScrollTranslation",
    "msScrollbar3dlightColor",
    "msScrollbarArrowColor",
    "msScrollbarBaseColor",
    "msScrollbarDarkshadowColor",
    "msScrollbarFaceColor",
    "msScrollbarHighlightColor",
    "msScrollbarShadowColor",
    "msScrollbarTrackColor",
    "msTextAutospace",
    "msTouchSelect",
    "msUserSelect",
    "msWrapFlow",
    "msWrapMargin",
    "msWrapThrough",
    "mt",
    "mx",
    "my",
    "objectFit",
    "objectPos",
    "objectPosition",
    "objectViewBox",
    "offset",
    "offsetAnchor",
    "offsetDistance",
    "offsetPath",
    "offsetPos",
    "offsetPosition",
    "offsetRotate",
    "opacity",
    "order",
    "orphans",
    "outline",
    "outlineColor",
    "outlineOffset",
    "outlineStyle",
    "outlineWidth",
    "overflow",
    "overflowAnchor",
    "overflowBlock",
    "overflowClipBox",
    "overflowClipMargin",
    "overflowInline",
    "overflowWrap",
    "overflowX",
    "overflowY",
    "overlay",
    "overscrollBehavior",
    "overscrollBehaviorBlock",
    "overscrollBehaviorInline",
    "overscrollBehaviorX",
    "overscrollBehaviorY",
    "p",
    "padding",
    "paddingBlock",
    "paddingBlockEnd",
    "paddingBlockStart",
    "paddingBottom",
    "paddingInline",
    "paddingInlineEnd",
    "paddingInlineStart",
    "paddingLeft",
    "paddingRight",
    "paddingTop",
    "page",
    "pageBreakAfter",
    "pageBreakBefore",
    "pageBreakInside",
    "paintOrder",
    "pathLength",
    "pb",
    "perspective",
    "perspectiveOrigin",
    "pl",
    "placeContent",
    "placeItems",
    "placeSelf",
    "pointerEvents",
    "pos",
    "position",
    "positionAnchor",
    "positionArea",
    "positionTry",
    "positionTryFallbacks",
    "positionTryOrder",
    "positionVisibility",
    "positioning",
    "pr",
    "printColorAdjust",
    "pt",
    "px",
    "py",
    "quotes",
    "r",
    "readingFlow",
    "readingOrder",
    "resize",
    "right",
    "rotate",
    "rowGap",
    "rubyAlign",
    "rubyMerge",
    "rubyOverhang",
    "rubyPosition",
    "rx",
    "ry",
    "scale",
    "scrollBehavior",
    "scrollInitialTarget",
    "scrollMargin",
    "scrollMarginBlock",
    "scrollMarginBlockEnd",
    "scrollMarginBlockStart",
    "scrollMarginBottom",
    "scrollMarginInline",
    "scrollMarginInlineEnd",
    "scrollMarginInlineStart",
    "scrollMarginLeft",
    "scrollMarginRight",
    "scrollMarginTop",
    "scrollMarkerGroup",
    "scrollPadding",
    "scrollPaddingBlock",
    "scrollPaddingBlockEnd",
    "scrollPaddingBlockStart",
    "scrollPaddingBottom",
    "scrollPaddingInline",
    "scrollPaddingInlineEnd",
    "scrollPaddingInlineStart",
    "scrollPaddingLeft",
    "scrollPaddingRight",
    "scrollPaddingTop",
    "scrollSnapAlign",
    "scrollSnapCoordinate",
    "scrollSnapDestination",
    "scrollSnapPointsX",
    "scrollSnapPointsY",
    "scrollSnapStop",
    "scrollSnapType",
    "scrollSnapTypeX",
    "scrollSnapTypeY",
    "scrollTargetGroup",
    "scrollTimeline",
    "scrollTimelineAxis",
    "scrollTimelineName",
    "scrollbarColor",
    "scrollbarGutter",
    "scrollbarWidth",
    "shapeImageThreshold",
    "shapeMargin",
    "shapeOutside",
    "shapeRendering",
    "speakAs",
    "stopColor",
    "stopOpacity",
    "stroke",
    "strokeColor",
    "strokeDasharray",
    "strokeDashoffset",
    "strokeLinecap",
    "strokeLinejoin",
    "strokeMiterlimit",
    "strokeOpacity",
    "strokeWidth",
    "tabSize",
    "tableLayout",
    "textAlign",
    "textAlignLast",
    "textAnchor",
    "textAutospace",
    "textBox",
    "textBoxEdge",
    "textBoxTrim",
    "textCombineUpright",
    "textDecoration",
    "textDecorationColor",
    "textDecorationInset",
    "textDecorationLine",
    "textDecorationSkip",
    "textDecorationSkipInk",
    "textDecorationStyle",
    "textDecorationThickness",
    "textEmphasis",
    "textEmphasisColor",
    "textEmphasisPosition",
    "textEmphasisStyle",
    "textFit",
    "textIndent",
    "textJustify",
    "textOrientation",
    "textOverflow",
    "textRendering",
    "textShadow",
    "textSizeAdjust",
    "textSpacingTrim",
    "textTransform",
    "textUnderlineOffset",
    "textUnderlinePosition",
    "textWrap",
    "textWrapMode",
    "textWrapStyle",
    "timelineScope",
    "timelineTrigger",
    "timelineTriggerActiveRange",
    "timelineTriggerName",
    "timelineTriggerSource",
    "top",
    "touchAction",
    "transform",
    "transformBox",
    "transformOrigin",
    "transformStyle",
    "transition",
    "transitionBehavior",
    "transitionDelay",
    "transitionDuration",
    "transitionProperty",
    "transitionTimingFunction",
    "translate",
    "triggerScope",
    "typography",
    "unicodeBidi",
    "userSelect",
    "vectorEffect",
    "verticalAlign",
    "viewTimeline",
    "viewTimelineAxis",
    "viewTimelineInset",
    "viewTimelineName",
    "viewTransitionClass",
    "viewTransitionName",
    "viewTransitionScope",
    "visibility",
    "w",
    "whiteSpace",
    "whiteSpaceCollapse",
    "widows",
    "width",
    "willChange",
    "wordBreak",
    "wordSpacing",
    "wordWrap",
    "writingMode",
    "x",
    "y",
    "zIndex",
    "zoom",
];

/// Props whose value may be a bare `<color>`, which is what makes a hex
/// literal there worth reporting as `hardcoded-color`.
///
/// Membership decides whether the rule runs at all, so an omission here is
/// a silent false negative rather than a missed suggestion. `bg` was the
/// expensive one: it is devup-ui's shorthand for `background` and the
/// Figma generator writes it for every solid fill, so `bg="#752E2E"` -
/// the single most common hardcoded color this repository produces - was
/// never examined by anything. That absence was then read as evidence
/// that the rule only fires when a matching token exists, which it does
/// not: `hardcoded-color` reports the literal either way and merely
/// attaches nearby tokens as a suggestion.
///
/// Deliberately excluded, and why:
/// - `colorScheme`, `colorInterpolationFilters`, `forcedColorAdjust`,
///   `printColorAdjust` take keywords, never a color.
/// - `MozBorderTopColors` and its siblings take a *list* of colors for
///   nested borders; a single hex is not the shape they are written in.
/// - `msScrollbar*Color` are IE-era and unreachable from devup-ui output.
/// - `caret` admits an optional color, but its color half is spelled
///   `caretColor` - which is here - and no generator emits the shorthand.
///
/// A shorthand earns a place here by being one the generated code
/// actually writes, which is the test `bg` passes and `caret` does not.
pub const DEVUP_COLOR_LIKE_PROPS: &[&str] = &[
    "WebkitTapHighlightColor",
    "WebkitTextFillColor",
    "WebkitTextStrokeColor",
    "accentColor",
    "backgroundColor",
    "bg",
    "bgColor",
    "borderBlockColor",
    "borderBlockEndColor",
    "borderBlockStartColor",
    "borderBottomColor",
    "borderColor",
    "borderInlineColor",
    "borderInlineEndColor",
    "borderInlineStartColor",
    "borderLeftColor",
    "borderRightColor",
    "borderTopColor",
    "caretColor",
    "color",
    "columnRuleColor",
    "fill",
    "floodColor",
    "lightingColor",
    "outlineColor",
    "scrollbarColor",
    "stopColor",
    "stroke",
    "strokeColor",
    "textDecorationColor",
    "textEmphasisColor",
];

pub const DEVUP_LENGTH_LIKE_PROPS: &[&str] = &[
    "bgSize",
    "borderBottomLeftRadius",
    "borderBottomRightRadius",
    "borderBottomWidth",
    "borderLeftWidth",
    "borderRadius",
    "borderRightWidth",
    "borderSpacing",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderTopWidth",
    "borderWidth",
    "bottom",
    "boxSize",
    "columnGap",
    "containIntrinsicBlockSize",
    "containIntrinsicHeight",
    "containIntrinsicInlineSize",
    "containIntrinsicSize",
    "containIntrinsicWidth",
    "flexBasis",
    "fontSize",
    "gap",
    "gridColumnGap",
    "gridGap",
    "gridRowGap",
    "h",
    "height",
    "left",
    "letterSpacing",
    "lineHeight",
    "m",
    "margin",
    "marginBottom",
    "marginLeft",
    "marginRight",
    "marginTop",
    "maxH",
    "maxHeight",
    "maxW",
    "maxWidth",
    "mb",
    "minH",
    "minHeight",
    "minW",
    "minWidth",
    "ml",
    "mr",
    "mt",
    "mx",
    "my",
    "outlineOffset",
    "outlineWidth",
    "overflowClipMargin",
    "p",
    "padding",
    "paddingBottom",
    "paddingLeft",
    "paddingRight",
    "paddingTop",
    "pb",
    "pl",
    "pr",
    "pt",
    "px",
    "py",
    "right",
    "rowGap",
    "shapeMargin",
    "strokeWidth",
    "tabSize",
    "top",
    "w",
    "width",
    "wordSpacing",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn style_prop_lists_are_sorted_for_binary_search() {
        let mut sorted = DEVUP_STYLE_PROPS.to_vec();
        sorted.sort_unstable();
        assert_eq!(DEVUP_STYLE_PROPS, sorted.as_slice());
        let mut colors = DEVUP_COLOR_LIKE_PROPS.to_vec();
        colors.sort_unstable();
        assert_eq!(DEVUP_COLOR_LIKE_PROPS, colors.as_slice());
        let mut lengths = DEVUP_LENGTH_LIKE_PROPS.to_vec();
        lengths.sort_unstable();
        assert_eq!(DEVUP_LENGTH_LIKE_PROPS, lengths.as_slice());
    }

    #[test]
    fn color_and_length_subsets_are_subsets_of_style_props() {
        for prop in DEVUP_COLOR_LIKE_PROPS {
            assert!(is_known_style_prop(prop), "{prop} missing from style props");
        }
        for prop in DEVUP_LENGTH_LIKE_PROPS {
            assert!(is_known_style_prop(prop), "{prop} missing from style props");
        }
    }

    /// A shorthand and the `*Color` spelling of the same property are the
    /// same property, and a caller picks whichever reads better. Covering
    /// one and not the other makes the rule depend on spelling: `bg` and
    /// `stroke` were unchecked while `bgColor` and `strokeColor`'s
    /// counterpart `stroke` were - so the same screen passed or failed on
    /// how its author had typed it.
    #[test]
    fn a_color_prop_and_its_shorthand_are_covered_together() {
        for (shorthand, long_form) in [
            ("bg", "backgroundColor"),
            ("bgColor", "backgroundColor"),
            ("stroke", "strokeColor"),
        ] {
            assert!(
                is_color_like_prop(shorthand),
                "{shorthand} is color-like but is not covered"
            );
            assert!(
                is_color_like_prop(long_form),
                "{long_form} is color-like but is not covered"
            );
        }
    }

    /// The physical border colors were covered and their logical
    /// equivalents were not, which is the same property written the way
    /// CSS writes it for a right-to-left document.
    #[test]
    fn logical_border_colors_are_covered_like_the_physical_ones() {
        for prop in [
            "borderBlockColor",
            "borderBlockStartColor",
            "borderBlockEndColor",
            "borderInlineColor",
            "borderInlineStartColor",
            "borderInlineEndColor",
        ] {
            assert!(is_color_like_prop(prop), "{prop} is not covered");
        }
    }

    /// Having "color" in the name is not what makes a prop color-valued.
    /// These four take keywords, and reporting a hex in them would be
    /// reporting something nobody can write.
    #[test]
    fn keyword_valued_props_named_color_are_not_color_like() {
        for prop in [
            "colorScheme",
            "colorInterpolationFilters",
            "forcedColorAdjust",
            "printColorAdjust",
        ] {
            assert!(
                is_known_style_prop(prop),
                "{prop} should still be a known style prop"
            );
            assert!(!is_color_like_prop(prop), "{prop} is not color-valued");
        }
    }

    #[test]
    fn recognizes_known_and_rejects_unknown_props() {
        assert!(is_known_style_prop("bg"));
        assert!(is_known_style_prop("borderRadius"));
        assert!(!is_known_style_prop("bgg"));
        assert!(is_color_like_prop("bgColor"));
        // `bg` is devup-ui's shorthand for `background` and what the Figma
        // generator writes for a solid fill. Excluding it meant the hardcoded
        // color the generator emits most often was the one color nothing
        // looked at.
        assert!(is_color_like_prop("bg"));
        assert!(is_length_like_prop("w"));
        assert!(is_known_non_style_prop("onClick"));
        assert!(is_known_non_style_prop("data-testid"));
        assert!(is_known_non_style_prop("_hover"));
        assert!(is_known_non_style_prop("as"));
    }
}
