//! Known `@devup-ui/react` primitive prop names, sourced verbatim from the
//! published Style Props API reference
//! (<https://github.com/dev-five-git/devup-ui/blob/main/apps/landing/src/app/(detail)/docs/api/style-props/page.mdx>),
//! not invented. `devup_ui_validate`'s `unknown-prop` rule checks JSX
//! attributes on the primitive elements it recognizes (`Box`, `Flex`,
//! `Text`, `Center`, `Grid`, `Image`) against this list plus a small set of
//! standard React/HTML/devup-ui-specific non-style props; anything else is
//! flagged rather than guessed at.
//!
//! `DEVUP_COLOR_LIKE_PROPS` / `DEVUP_LENGTH_LIKE_PROPS` are the subsets
//! whose CSS-property counterpart is a single color or length value; they
//! drive the `hardcoded-color` / `hardcoded-length` / `unknown-token`
//! rules. Deliberately conservative: composite props like `background`
//! (can hold a gradient) or `border` (shorthand for width+style+color) are
//! excluded from both subsets rather than guessed at, since flagging them
//! incorrectly would repeat exactly the fabrication failure this tool
//! exists to prevent.

/// devup-ui primitive components whose JSX props this validator checks
/// against [`DEVUP_STYLE_PROPS`] for the `unknown-prop` rule. Custom
/// component names are never flagged: unlike these primitives, a custom
/// component's valid prop set cannot be known statically from devup-ui's
/// public docs, so guessing which props it accepts would risk exactly the
/// kind of invented-fact failure this tool exists to prevent.
pub const DEVUP_PRIMITIVE_ELEMENTS: &[&str] = &["Box", "Flex", "Text", "Center", "Grid", "Image"];

/// Non-style props every devup-ui primitive additionally accepts: standard
/// React/HTML attributes, event handlers, and devup-ui-specific structural
/// props (`as`, `selectors`). Checked case-sensitively against the exact
/// attribute name; `data-*`/`aria-*` and pseudo-state (`_hover`, `_dark`,
/// ...) / responsive-condition props are matched by prefix separately in
/// `is_known_non_style_prop`.
const DEVUP_NON_STYLE_PROPS: &[&str] = &[
    "as",
    "selectors",
    "children",
    "className",
    "style",
    "id",
    "key",
    "ref",
    "role",
    "tabIndex",
    "title",
    "htmlFor",
    "for",
    "colSpan",
    "rowSpan",
    "type",
    "name",
    "value",
    "defaultValue",
    "placeholder",
    "disabled",
    "checked",
    "defaultChecked",
    "readOnly",
    "required",
    "min",
    "max",
    "step",
    "rows",
    "cols",
    "src",
    "srcSet",
    "alt",
    "sizes",
    "loading",
    "decoding",
    "href",
    "target",
    "rel",
    "download",
    "autoFocus",
    "autoComplete",
    "form",
    "multiple",
    "accept",
    "list",
    "pattern",
    "spellCheck",
    "draggable",
    "contentEditable",
    "suppressHydrationWarning",
];

/// Returns true for props no primitive-specific check should ever flag:
/// standard React/HTML attributes, `on*` event handlers, `data-*`/`aria-*`,
/// and devup-ui pseudo-state / responsive-condition props (which are
/// user-defined selector keys, not a fixed enumerable set).
pub fn is_known_non_style_prop(name: &str) -> bool {
    DEVUP_NON_STYLE_PROPS.contains(&name)
        || name.starts_with("on")
        || name.starts_with("data-")
        || name.starts_with("aria-")
        || name.starts_with('_')
}

pub fn is_known_style_prop(name: &str) -> bool {
    DEVUP_STYLE_PROPS.binary_search(&name).is_ok()
}

pub fn is_color_like_prop(name: &str) -> bool {
    DEVUP_COLOR_LIKE_PROPS.binary_search(&name).is_ok()
}

pub fn is_length_like_prop(name: &str) -> bool {
    DEVUP_LENGTH_LIKE_PROPS.binary_search(&name).is_ok()
}

pub const DEVUP_STYLE_PROPS: &[&str] = &[
    "accentColor",
    "alignContent",
    "alignItems",
    "alignSelf",
    "alignmentBaseline",
    "animation",
    "animationComposition",
    "animationDelay",
    "animationDir",
    "animationDirection",
    "animationDuration",
    "animationFillMode",
    "animationIterationCount",
    "animationName",
    "animationPlayState",
    "animationTimeline",
    "animationTimingFunction",
    "appearance",
    "aspectRatio",
    "backdropFilter",
    "backfaceVisibility",
    "background",
    "backgroundAttachment",
    "backgroundBlendMode",
    "backgroundClip",
    "backgroundColor",
    "backgroundImage",
    "backgroundOrigin",
    "backgroundPosition",
    "backgroundPositionX",
    "backgroundPositionY",
    "backgroundRepeat",
    "backgroundSize",
    "bg",
    "bgAttachment",
    "bgClip",
    "bgColor",
    "bgImage",
    "bgOrigin",
    "bgPosition",
    "bgPositionX",
    "bgPositionY",
    "bgRepeat",
    "bgSize",
    "border",
    "borderBottom",
    "borderBottomColor",
    "borderBottomLeftRadius",
    "borderBottomRightRadius",
    "borderBottomStyle",
    "borderBottomWidth",
    "borderCollapse",
    "borderColor",
    "borderImage",
    "borderImageOutset",
    "borderImageRepeat",
    "borderImageSlice",
    "borderImageSource",
    "borderImageWidth",
    "borderLeft",
    "borderLeftColor",
    "borderLeftStyle",
    "borderLeftWidth",
    "borderRadius",
    "borderRight",
    "borderRightColor",
    "borderRightStyle",
    "borderRightWidth",
    "borderSpacing",
    "borderStyle",
    "borderTop",
    "borderTopColor",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderTopStyle",
    "borderTopWidth",
    "borderWidth",
    "bottom",
    "boxShadow",
    "boxSize",
    "boxSizing",
    "captionSide",
    "caret",
    "caretColor",
    "caretShape",
    "clear",
    "clipPath",
    "clipRule",
    "color",
    "colorScheme",
    "columnGap",
    "containIntrinsicBlockSize",
    "containIntrinsicHeight",
    "containIntrinsicInlineSize",
    "containIntrinsicSize",
    "containIntrinsicWidth",
    "content",
    "cursor",
    "display",
    "dominantBaseline",
    "emptyCells",
    "fill",
    "filter",
    "flex",
    "flexBasis",
    "flexDir",
    "flexDirection",
    "flexFlow",
    "flexGrow",
    "flexShrink",
    "flexWrap",
    "float",
    "font",
    "fontFamily",
    "fontFeatureSettings",
    "fontKerning",
    "fontLanguageOverride",
    "fontOpticalSizing",
    "fontSize",
    "fontSizeAdjust",
    "fontStretch",
    "fontStyle",
    "fontSynthesis",
    "fontVariant",
    "fontVariantAlternates",
    "fontVariantCaps",
    "fontVariantEastAsian",
    "fontVariantLigatures",
    "fontVariantNumeric",
    "fontVariantPosition",
    "fontVariationSettings",
    "fontWeight",
    "forcedColorAdjust",
    "gap",
    "grid",
    "gridArea",
    "gridAutoColumns",
    "gridAutoFlow",
    "gridAutoRows",
    "gridColumn",
    "gridColumnEnd",
    "gridColumnGap",
    "gridColumnStart",
    "gridGap",
    "gridRow",
    "gridRowEnd",
    "gridRowGap",
    "gridRowStart",
    "gridTemplate",
    "gridTemplateAreas",
    "gridTemplateColumns",
    "gridTemplateRows",
    "h",
    "hangingPunctuation",
    "height",
    "hyphenateLimitChars",
    "hyphens",
    "imageOrientation",
    "imageRendering",
    "imageResolution",
    "initialLetter",
    "inset",
    "insetBlock",
    "insetBlockEnd",
    "insetBlockStart",
    "insetInline",
    "insetInlineEnd",
    "insetInlineStart",
    "isolation",
    "justifyContent",
    "justifyItems",
    "justifySelf",
    "left",
    "letterSpacing",
    "lineBreak",
    "lineHeight",
    "listStyle",
    "listStyleImage",
    "listStylePosition",
    "listStyleType",
    "m",
    "margin",
    "marginBottom",
    "marginLeft",
    "marginRight",
    "marginTop",
    "mask",
    "maskBorder",
    "maskBorderMode",
    "maskBorderOutset",
    "maskBorderRepeat",
    "maskBorderSlice",
    "maskBorderSource",
    "maskBorderWidth",
    "maskClip",
    "maskComposite",
    "maskImage",
    "maskMode",
    "maskOrigin",
    "maskPosition",
    "maskRepeat",
    "maskSize",
    "maskType",
    "maxH",
    "maxHeight",
    "maxW",
    "maxWidth",
    "mb",
    "minH",
    "minHeight",
    "minW",
    "minWidth",
    "mixBlendMode",
    "ml",
    "mr",
    "mt",
    "mx",
    "my",
    "objectFit",
    "objectPosition",
    "offset",
    "offsetAnchor",
    "offsetDistance",
    "offsetPath",
    "offsetPosition",
    "offsetRotate",
    "opacity",
    "order",
    "outline",
    "outlineColor",
    "outlineOffset",
    "outlineStyle",
    "outlineWidth",
    "overflow",
    "overflowBlock",
    "overflowClipMargin",
    "overflowInline",
    "overflowWrap",
    "overflowX",
    "overflowY",
    "overscrollBehavior",
    "overscrollBehaviorBlock",
    "overscrollBehaviorInline",
    "overscrollBehaviorX",
    "overscrollBehaviorY",
    "p",
    "padding",
    "paddingBottom",
    "paddingLeft",
    "paddingRight",
    "paddingTop",
    "pb",
    "perspective",
    "perspectiveOrigin",
    "pl",
    "placeContent",
    "placeItems",
    "placeSelf",
    "pointerEvents",
    "pos",
    "position",
    "pr",
    "printColorAdjust",
    "pt",
    "px",
    "py",
    "resize",
    "right",
    "rotate",
    "rowGap",
    "scale",
    "scrollBehavior",
    "scrollbarColor",
    "scrollbarGutter",
    "scrollbarWidth",
    "shapeImageThreshold",
    "shapeMargin",
    "shapeOutside",
    "stroke",
    "strokeOpacity",
    "strokeWidth",
    "tabSize",
    "tableLayout",
    "textAlign",
    "textAlignLast",
    "textDecoration",
    "textDecorationColor",
    "textDecorationLine",
    "textDecorationStyle",
    "textEmphasis",
    "textEmphasisColor",
    "textEmphasisPosition",
    "textEmphasisStyle",
    "textIndent",
    "textJustify",
    "textOverflow",
    "textRendering",
    "textShadow",
    "textSizeAdjust",
    "textTransform",
    "textWrap",
    "top",
    "transform",
    "transformBox",
    "transformOrigin",
    "transformStyle",
    "transition",
    "transitionDelay",
    "transitionDuration",
    "transitionProperty",
    "transitionTimingFunction",
    "translate",
    "typography",
    "userSelect",
    "verticalAlign",
    "viewTransitionName",
    "w",
    "whiteSpace",
    "whiteSpaceCollapse",
    "width",
    "wordBreak",
    "wordSpacing",
    "zIndex",
];

pub const DEVUP_COLOR_LIKE_PROPS: &[&str] = &[
    "accentColor",
    "backgroundColor",
    "bgColor",
    "borderBottomColor",
    "borderColor",
    "borderLeftColor",
    "borderRightColor",
    "borderTopColor",
    "caretColor",
    "color",
    "fill",
    "outlineColor",
    "scrollbarColor",
    "stroke",
    "textDecorationColor",
    "textEmphasisColor",
];

pub const DEVUP_LENGTH_LIKE_PROPS: &[&str] = &[
    "bgSize",
    "borderBottomLeftRadius",
    "borderBottomRightRadius",
    "borderBottomWidth",
    "borderLeftWidth",
    "borderRadius",
    "borderRightWidth",
    "borderSpacing",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderTopWidth",
    "borderWidth",
    "bottom",
    "boxSize",
    "columnGap",
    "containIntrinsicBlockSize",
    "containIntrinsicHeight",
    "containIntrinsicInlineSize",
    "containIntrinsicSize",
    "containIntrinsicWidth",
    "flexBasis",
    "fontSize",
    "gap",
    "gridColumnGap",
    "gridGap",
    "gridRowGap",
    "h",
    "height",
    "left",
    "letterSpacing",
    "lineHeight",
    "m",
    "margin",
    "marginBottom",
    "marginLeft",
    "marginRight",
    "marginTop",
    "maxH",
    "maxHeight",
    "maxW",
    "maxWidth",
    "mb",
    "minH",
    "minHeight",
    "minW",
    "minWidth",
    "ml",
    "mr",
    "mt",
    "mx",
    "my",
    "outlineOffset",
    "outlineWidth",
    "overflowClipMargin",
    "p",
    "padding",
    "paddingBottom",
    "paddingLeft",
    "paddingRight",
    "paddingTop",
    "pb",
    "pl",
    "pr",
    "pt",
    "px",
    "py",
    "right",
    "rowGap",
    "shapeMargin",
    "strokeWidth",
    "tabSize",
    "top",
    "w",
    "width",
    "wordSpacing",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn style_prop_lists_are_sorted_for_binary_search() {
        let mut sorted = DEVUP_STYLE_PROPS.to_vec();
        sorted.sort_unstable();
        assert_eq!(DEVUP_STYLE_PROPS, sorted.as_slice());
        let mut colors = DEVUP_COLOR_LIKE_PROPS.to_vec();
        colors.sort_unstable();
        assert_eq!(DEVUP_COLOR_LIKE_PROPS, colors.as_slice());
        let mut lengths = DEVUP_LENGTH_LIKE_PROPS.to_vec();
        lengths.sort_unstable();
        assert_eq!(DEVUP_LENGTH_LIKE_PROPS, lengths.as_slice());
    }

    #[test]
    fn color_and_length_subsets_are_subsets_of_style_props() {
        for prop in DEVUP_COLOR_LIKE_PROPS {
            assert!(is_known_style_prop(prop), "{prop} missing from style props");
        }
        for prop in DEVUP_LENGTH_LIKE_PROPS {
            assert!(is_known_style_prop(prop), "{prop} missing from style props");
        }
    }

    #[test]
    fn recognizes_known_and_rejects_unknown_props() {
        assert!(is_known_style_prop("bg"));
        assert!(is_known_style_prop("borderRadius"));
        assert!(!is_known_style_prop("bgg"));
        assert!(is_color_like_prop("bgColor"));
        assert!(!is_color_like_prop("bg"));
        assert!(is_length_like_prop("w"));
        assert!(is_known_non_style_prop("onClick"));
        assert!(is_known_non_style_prop("data-testid"));
        assert!(is_known_non_style_prop("_hover"));
        assert!(is_known_non_style_prop("as"));
    }
}
